### ISSUE TITLE
remove Angular from dist JS file  

### ISSUE THREAD

**Issue by oxmo456** [simeg/ngjs-color-picker#14]
It seems that the distribued JS file contain AngularJS dependency. Could you please remove AngularJS from the distribued JS file?

**Comment by simeg** [comment]
Hmm yeah, it looks like it's in there. I'll look at it.

**Comment by simeg** [comment]
@oxmo456 this is now done. Version `1.1.2` is released. Thanks so much for reporting this.

The size decreased by 166KB thanks to this! 🙌

**Comment by oxmo456** [comment]
@simeg you're welcome! thank you :)
