### ISSUE TITLE
Use ng-model and add ng-change

### ISSUE THREAD

**Issue by sibelius** [simeg/ngjs-color-picker#2]
Ng-model enables us to to validation on a form, and it's also a good practice

Here is an article that describes how to do it: http://www.chroder.com/2014/02/01/using-ngmodelcontroller-with-custom-directives/

ng-change is also very useful for custom directives. (maybe to provide a transformation of the model value)

The accepted answer of this post explain how to implement it: http://stackoverflow.com/questions/24754005/how-to-implement-an-ng-change-for-a-custom-directive

Thanks

**Comment by simeg** [comment]
Feel free to create a PR for this, otherwise I'll do it whenever I get the time.

**Comment by Laurens-makel** [comment]
I got it working with the following:

```
scope.pick = function(color) {
                    scope.selectedColor = color;
                    element.controller('ngModel').$viewChangeListeners[0]();
                };

                scope.updateModel = function(color){
                	ctrl.$setViewValue(color);
                	element.controller('ngModel').$viewChangeListeners[0]();
                }`
