### ISSUE TITLE
customColors not works

### ISSUE THREAD

**Issue by cmoseses** [simeg/ngjs-color-picker#7]
it could only works after I replace all the `customColors` into `customcolors` in source code

**Comment by simeg** [comment]
Could you provide some code to display the bug?

**Comment by cmoseses** [comment]
Sorry, my mistake. I should pass `custom-colors` instead of `customColors` in directive
in [the demo of ngjs](https://plnkr.co/edit/3kxqdkOISLD4n0b7kbgI?p=preview)
