### ISSUE TITLE
update documentation, selected attribute is renamed to selectedColor

### ISSUE THREAD

**Issue by nulayuhz** [simeg/ngjs-color-picker#9]
Hi simeg,

On http://simeg.github.io/ngjs-color-picker/#/  and the demos are still using the selected="" attribute even though in the code it is renamed to selectedColor.

thanks

**Comment by simeg** [comment]
Hi @ahlunju, thanks! I was wondering why the demo stopped working.

Fixed in db1207b2fe0d625e0bf60be0ddc29f5050d5283c.
